baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gabriel Coelho'
theme="archie"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 1

[params]
  customCSS = ["css/custom.css"]