baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gabriel Coelho'
theme="archie"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gabrieljdcoelho"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/gabrielcoelhoo/"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 4


[params]
  customCSS = ["css/custom.css"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'